<footer class="mainfooter">
    <div id="Footer">
        <div class="social">
            <h3>Contact</h3>
            <hr>
            <p> Location: 2420 Cleveland Ave N, Roseville, MN 55113</p>
             <p> Phone: 651-896-0964</p>
        </div>
        <div class="social">
            <h3>Stay Connected</h3>
            <hr>
            <a class="social facebook" href=""><img src="Images/facebook-icon.png">
            </a>
            <a class="social twitter" href=""><img src="Images/twitter-icon.png">
            </a></br>
            <a class="social instagram" href=""><img src="Images/Instagram-icon.png">
            </a>
            <a class="social gmail" href=""><img src="Images/G-mail-icon.png">
            </a>
        </div>
    </div>
</footer>
</body>
</html>