<html>
<head>
    <link href="Layout.css" rel="stylesheet" type="text/css">
    <link href="Menu.css" rel="stylesheet" type="text/css">
</head>
<body>
<div id="Holder">
    <div id="Header"></div>
    <div id="NavBar">
        <nav>
            <ul>
                <li><a href= Index.php>Home</a></li>
                <li><a href= Facilites.php>Facilites</a></li>
                <li><a href= Login.php>Login</a></li>
                <li><a href= forms.php>Register</a></li>
            </ul>
        </nav>
    </div>